trigger: none

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-tests.yml
  parameters:
    ServiceDirectory: textanalytics
    Clouds: 'Public,Canary'
    CloudConfig:
      Public:
        SubscriptionConfiguration: $(sub-config-storage-test-resources)
      Canary:
        SubscriptionConfiguration: $(sub-config-storage-test-resources)
        Location: 'centraluseuap'
